### ISSUE TITLE
Handle OAuth errors from GDrive

### ISSUE THREAD

**Issue by jwrubel** [learningtapestry/canvas-google-drive-connector#13]
In the process of testing I'm encountering a 502 error from the application when using the file browser in Canvas. There's no handler so the screen just shows the spinner indefinitely. We should ideally handle 500 and other types of errors and present a useful message to the end user in Canvas.

**Comment by andersoncardoso** [comment]
Done on https://github.com/learningtapestry/canvas-google-drive-connector/pull/17
