### ISSUE TITLE
404 error adding item to course content

### ISSUE THREAD

**Issue by joehobson** [learningtapestry/canvas-google-drive-connector#24]
Trying to add a Google Drive item to course content, i'm getting a "Not Found" error.

1. Open a course as an editor, add a module if you don't already have one
1. Click the plus sign next to the module to add an item to it
1. select "External Tool" from the drop-down
1. select Google Drive from the list of tools

![google drive not found error](https://user-images.githubusercontent.com/838671/37698312-366bcbda-2cb0-11e8-9328-cdc751094bf8.png)

**Comment by jwrubel** [comment]
@joehobson I suspect this is related to the configuration on testcanvas.aps.edu . Can you try the same process on https://canvas.navigationnorth.com/ and see if that works? I'll connect with you diretctly to see if I can get access to troubleshoot the testcanvas.aps.edu server.

**Comment by joehobson** [comment]
Same issue on the NN staging server. Sorry, forgot to mention that earlier

**Comment by jwrubel** [comment]
ok I've confirmed this is a problem in both environments, and only when trying to add an item to a course through the External Tool menu. It's trying to invoke from `/google-lti/lti/link-selection`.

This same error occurs when using the locally-hosted version mapped to `/google-lti` and also the externally-hosted one on Cloud66. @andersoncardoso could you take a look?

**Comment by jwrubel** [comment]
I know I had tested this successfully back before the most recent round of updates and it worked so it's possible some change since `c35e66b` caused the issue.

**Comment by andersoncardoso** [comment]
@joehobson @jwrubel 

Done on https://github.com/learningtapestry/canvas-google-drive-connector/pull/25

PS: the file being selected should be "public", i.e.: shared as "anyone with the link can view"


![1](https://user-images.githubusercontent.com/597026/37723437-27504aa6-2d0d-11e8-8c7c-f18bd43e3c37.png)
![2](https://user-images.githubusercontent.com/597026/37723438-2773bf68-2d0d-11e8-8a99-b7c1945cc014.png)
![3](https://user-images.githubusercontent.com/597026/37723439-279e11dc-2d0d-11e8-8193-bb7ab055dd68.png)
![4](https://user-images.githubusercontent.com/597026/37723440-28128d46-2d0d-11e8-8635-78fccaeadfc8.png)
![5](https://user-images.githubusercontent.com/597026/37723442-2853f286-2d0d-11e8-975e-3ba9fdb615a1.png)
