### ISSUE TITLE
No key/pair credentials for xxxxxxx-xxxxxxx.apps.googleusercontent.com

### ISSUE THREAD

**Issue by shawniverson** [learningtapestry/canvas-google-drive-connector#28]
Having trouble with the LTI integration with Canvas (stable build 06/09/18) and master branch of canvas-google-drive-connector.

Receiving No key/pair credentials, as if the secret is not being passed to the application.

**Comment by shawniverson** [comment]
I cheated for the moment and hard coded the secret into lti_auth.rb, next I'm going to capture the post data and see what is going on...

**Comment by shawniverson** [comment]
Well now, I encrypted my traffic over https 🤣 hrm...

**Comment by jwrubel** [comment]
Hi @shawniverson - This one's going to be a little harder to debug. The key and secret are referenced as environment variables in the app. Depending on where you have the connector deployed, there are a number of ways to do that. Is your instance deployed to a public cloud like AWS, GAE, or Azure? Or is this a private server somewhere?

**Comment by shawniverson** [comment]
@jwrubel private server.  lti_auth.rb doesn't seem to use the environment variables and is relying on the POST data for the LTI integration, and for whatever reason, the Client ID is traversing, but Shared Secret is not.

**Comment by andersoncardoso** [comment]
Have you created a key/secret pair on `/credentials/new` and used them on your LTI app config (inside canvas) ?
In summary:
- create a pair on `/credentials/new`
- on the canvas LTI app config, point to the `/config.xml` and use the generated values 
- then the LTI requests will send this info (canvas does this automatically) for us to authenticate 

The key/secret used on the LTI requests are different than the ones on env vars. 
The environment vars are for session and google-drive's oauth2. 
LTI  also uses oauth, but it's different than google's. The key is passed via the key `oauth_consumer_key` param and we used it to check the encrypted challenge with the ones stored on our side. 
All this process should be transparent after config.

![1](https://user-images.githubusercontent.com/597026/41428586-eb54e522-6fe0-11e8-98e9-1c98ad262594.png)
![2](https://user-images.githubusercontent.com/597026/41428588-eb7d7780-6fe0-11e8-9c80-d099e85621be.png)
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/597026/41428589-ebb811e2-6fe0-11e8-8d31-63230b89b19a.png">

**Comment by andersoncardoso** [comment]
just to elaborate:
LTI oauth1 does a symmetric encryption (shared secret) to authenticate content.
- we create a key/value we send this pair once to canvas
- canvas sign the content using the secret and then send us only the key and the cyphered message
- on our side we grab the request key to find the stored secret, and then use it to decypher the message and authenticate.

**Comment by shawniverson** [comment]
@andersoncardoso I will give this a try, it appears I am confusing two different sets of keys (the google drive API ones, and the LTI app ones....ooops).

**Comment by shawniverson** [comment]
@andersoncardoso That was it.  I was using the wrong credentials and needed to generate them from the LTI app.

**Comment by jwrubel** [comment]
This is a very confusing part of the LTI process - I'll take some time to improve our documentation on this.

**Comment by kalemayur** [comment]
Thank You andersoncardoso. It's working now.
