### ISSUE TITLE
Giant icon in Editor

### ISSUE THREAD

**Issue by shawniverson** [learningtapestry/canvas-google-drive-connector#29]
![image](https://user-images.githubusercontent.com/6255179/41205847-d894524e-6cc8-11e8-9831-186194251062.png)

**Comment by jwrubel** [comment]
Hi @shawniverson thanks for opening this! I made a quick PR to resize the icon to 16x16. Can you let me know what browser you saw this in so we can verify the change? I've only used this plugin with Chrome and we don't experience this issue.

**Comment by shawniverson** [comment]
@jwrubel Chrome version 67
